
spring:
  redis:
    host: 47.103.202.12
    port: 6379
    password: codeAnt.+AAredis
    # 连接超时时间（记得添加单位，Duration）
    timeout: 10000ms
    # Redis默认情况下有16个分片，这里配置具体使用的分片
    database: 10
    lettuce:
      pool:
        # 连接池最大连接数（使用负值表示没有限制） 默认 8
        max-active: 8
        # 连接池最大阻塞等待时间（使用负值表示没有限制） 默认 -1
        max-wait: -1ms
        # 连接池中的最大空闲连接 默认 8
        max-idle: 8
        # 连接池中的最小空闲连接 默认 0
        min-idle: 0


  datasource:
    url: jdbc:mysql://47.103.202.12:33306/codeant_miaosha?useUnicode=true&characterEncoding=utf8 #不需要\作为转移字符
    username: root
    password: codeAnt.+AA123
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver #com.mysql.jdbc.Driver更换驱动
    druid.filters: stat
    druid.maxActive: 20
    druid.initialSize: 1
    druid.maxWait: 60000
    druid.minIdle: 1
    druid.timeBetweenEvictionRunsMillis: 60000
    druid.minEvictableIdleTimeMillis: 300000
    druid.validationQuery: select 'x'
    druid.testWhileIdle: true
    druid.testOnBorrow: false
    druid.testOnReturn: false
    druid.poolPreparedStatements: true
    druid.maxOpenPreparedStatements: 20


## 该配置节点为独立的节点，有很多同学容易将这个配置放在spring的节点下，导致配置无法被识别
mybatis:
  mapper-locations: classpath:mapper/*.xml  #注意：一定要对应mapper映射xml文件的所在路径
  type-aliases-package: com.example.miaoshademo.entity  # 注意：对应实体类的路径
  configuration:
    #这个配置使全局的映射器启用或禁用缓存
    cache-enabled: true
    #对于未知的SQL查询，允许返回不同的结果集以达到通用的效果
    multiple-result-sets-enabled: true
    #配置默认的执行器。SIMPLE 执行器没有什么特别之处。REUSE 执行器重用预处理语句。BATCH 执行器重用语句和批量更新
    default-executor-type: REUSE
    #全局启用或禁用延迟加载。当禁用时，所有关联对象都会即时加载。
    lazy-loading-enabled: false
    aggressive-lazy-loading: true
    #设置超时时间，它决定驱动等待一个数据库响应的时间
    default-statement-timeout: 25000
server:
  servlet:
    context-path: /ms
  port: 9090